---
title: "Proyecto"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---

```{r echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, comment = NA)
```


```{r echo = FALSE}
suppressMessages(library(flexdashboard,quietly =TRUE))
suppressMessages(library(dplyr,quietly =TRUE))
suppressMessages(library(tidyr,quietly =TRUE))
suppressMessages(library(stringr,quietly =TRUE))
suppressMessages(library(expss,quietly =TRUE))
suppressMessages(library(highcharter,quietly =TRUE))
suppressMessages(library(kableExtra,quietly =TRUE))
suppressMessages(library(psych,quietly =TRUE))
suppressMessages(library(wordcloud,quietly =TRUE))
suppressMessages(library(readr,quietly =TRUE))
data.total <- suppressMessages(read_spss('~/R/r-projects/09.iocs2022/Datos_IOCS2022.sav'))
data.total <- filter(data.total, DURACION > 0)
data <- data.total
options(width=9999)

## TABLERO DE ESTUDIO
xx <- length(data$ESTADO[data$ESTADO==1 | data$ESTADO==5 | data$ESTADO==6 | data$ESTADO==9]) # finalizadas estados = 1, 5, 6, 9
xy <- length(data$ESTADO[(data$ESTADO==0 & data$DURACION>0) | data$ESTADO==2 ]) # parciales estados = 0, 2
xz <- length(data$ESTADO[data$ESTADO==3 | (data$ESTADO==4 & data$DURACION>0) | data$ESTADO==7 | data$ESTADO==8 | data$ESTADO==10 ]) # rechazadas estados = 3, 4, 7, 8, 10
xw <- xx+xy+xz
xn <- 400 # muestra teórica
duracion <- round(mean(data$DURACION[data$ESTADO==1 | data$ESTADO==5 | data$ESTADO==6 | data$ESTADO==9], na.rm=TRUE)/60,2)
#xx finalizadas
#xy parciales
#xz rechazadas
#xw contactos
#xn muestra

# tasa
tasa <- round(100*(xx/xw),1)
# % finalizadas
gtasa1 <- highchart() %>% 
    hc_chart(type = 'solidgauge') %>%
    hc_pane(startAngle = -90,endAngle = 90,background = list(outerRadius = '100%',innerRadius = '60%',shape = 'arc')) %>%
    hc_tooltip(enabled = FALSE) %>%
    hc_yAxis(lineWidth = 0,minorTickWidth = 0,tickAmount = 2,min = 0,max = 100,labels = list(y = 25)) %>%
    hc_add_series(round(100*(xx/xn),1),dataLabels = list(borderWidth = 0,useHTML = TRUE,style = list(fontSize = '2em'))) %>%
    hc_credits(enabled = TRUE,text = 'InvestigaOnline.com',href = 'https://www.investigaonline.com') %>%
    hc_exporting(enabled = TRUE) %>%
    hc_plotOptions(series = list(animation = FALSE))

# parciales
gtasa2 <- highchart() %>% 
    hc_chart(type = 'solidgauge') %>%
    hc_pane(startAngle = -90,endAngle = 90,background = list(outerRadius = '100%',innerRadius = '60%',shape = 'arc')) %>%
    hc_tooltip(enabled = FALSE) %>%
    hc_yAxis(lineWidth = 0,minorTickWidth = 0,tickAmount = 2,min = 0,max = 100,labels = list(y = 25)) %>%
    hc_add_series(round(100*(xy/xn),1),dataLabels = list(borderWidth = 0,useHTML = TRUE,style = list(fontSize = '2em'))) %>%
    hc_credits(enabled = TRUE,text = 'InvestigaOnline.com',href = 'https://www.investigaonline.com') %>%
    hc_exporting(enabled = TRUE) %>%
    hc_plotOptions(series = list(animation = FALSE))


# rechazos
gtasa3 <- highchart() %>% 
    hc_chart(type = 'solidgauge') %>%
    hc_pane(startAngle = -90,endAngle = 90,background = list(outerRadius = '100%',innerRadius = '60%',shape = 'arc')) %>%
    hc_tooltip(enabled = FALSE) %>%
    hc_yAxis(lineWidth = 0,minorTickWidth = 0,tickAmount = 2,min = 0,max = 100,labels = list(y = 25)) %>%
    hc_add_series(round(100*(xz/xn),1),dataLabels = list(borderWidth = 0,useHTML = TRUE,style = list(fontSize = '2em'))) %>%
    hc_credits(enabled = TRUE,text = 'InvestigaOnline.com',href = 'https://www.investigaonline.com') %>%
    hc_exporting(enabled = TRUE) %>%
    hc_plotOptions(series = list(animation = FALSE))

data$FECHAFIN <- as.Date(data$FECHAFIN,"%d/%m/%Y")
data$FECHAINI <- as.Date(data$FECHAINI,"%d/%m/%Y")
df <- as.data.frame(data %>% filter(ESTADO %in% c(1,5,6,9)) %>% group_by(FECHAFIN) %>% arrange(FECHAFIN) %>% summarise(Entrevistas=n()))
dia <- hchart(df, 'spline', hcaes(x=FECHAFIN, y=Entrevistas))%>%
    hc_credits(enabled = TRUE,text = 'InvestigaOnline.com',href = 'https://www.investigaonline.com') %>%
    hc_exporting(enabled = TRUE) %>%
    hc_plotOptions(series = list(animation = FALSE))

#gráfico timeline
name=c("inicio",
        "lanzamiento",
        "entrevistas ",
        "contactos", 
        "duración", 
        "final")
label=c(paste("alta estudio: ",min(data$FECHAINI, na.rm=TRUE)), 
        paste("primera: ",min(data$FECHAFIN, na.rm=TRUE)), 
        paste("finalizadas ",xx), 
        paste("total ",xw), 
        paste("duración: ",duracion," minutos"), 
        paste("última: ",max(data$FECHAFIN, na.rm=TRUE)))
description=c(min(data$FECHAINI, na.rm=TRUE), 
        min(data$FECHAFIN, na.rm=TRUE), 
        xx, 
        xw, 
        duracion, 
        max(data$FECHAFIN, na.rm=TRUE))
tml <- data.frame(name, label, description)

timeline <- highchart() %>%
    hc_chart(type = 'timeline') %>%
    hc_xAxis(visible = FALSE) %>%
    hc_yAxis(visible = FALSE) %>%
    hc_legend(enable=FALSE) %>%
    hc_title(text = var_lab(data$ESTUDIO)) %>%
    hc_tooltip(enabled=FALSE) %>%
    hc_colors(c('#4185F3','#427CDD','#406AB2','#3E5A8E','#3B4A68','#363C46')) %>%
    hc_add_series(data=tml, name='Timeline', keys=c('name', 'label', 'description'))%>%
    hc_credits(enabled = TRUE,text = 'InvestigaOnline.com',href = 'https://www.investigaonline.com') %>%
    hc_exporting(enabled = TRUE) %>%
    hc_plotOptions(series = list(animation = FALSE))
```

Datos
=====================================

Column
-------------------------------------

### Muestra

`r valueBox(xn, caption = 'muestra diseñada', icon = 'fa-users', color = '#80bdff')`

### Contactos

`r valueBox(xw, caption = 'contactos', icon = 'fa-user-circle-o', color = '#b6babe')`

### Entrevistas acabadas

`r valueBox(xx, caption = 'finalizadas', icon = 'fa-check-circle', color = '#8bd1dc')`

### Parciales

`r valueBox(xy, caption = 'parciales', icon = 'fa-calendar-o', color = '#f5b2ac')`

### Rechazadas

`r valueBox(xz, caption = 'rechazadas', icon = 'fa-ban', color = '#ffe083')`

### Duración

`r valueBox(duracion, caption = 'duracion minutos', icon = 'fa-clock', color = '#ffaa04')`

Column
-------------------------------------

### **Completas**

`r gtasa1`

### **Parciales**  

`r gtasa2`

### **Rechazadas**

`r gtasa3`

Column
------------------------------------

### **Nº de Entrevistas día**

`r dia`

### Timeline del proyecto

`r timeline`

```{r echo=FALSE}
set.seed(311265)
data <- suppressMessages(read_spss('~/R/r-projects/09.iocs2022/Datos_IOCS2022.sav'))
data <- data %>%  where(ESTADO %in% c(1,5,6,9))
options(highcharter.theme = hc_theme_bloom(tooltip = list(valueDecimals = 1)))
```
