---
title: "Resultados (07)"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

El objetivo 7 hacía referencia al uso de los probadores en las tiendas físicas de la marca analizada. 

```{r echo = FALSE}
tab <- data %>%
	tab_cells(P7) %>%
	tab_stat_cpct(label='% casos') %>%
    tab_cells(P7) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_pivot() %>%
    tab_caption('Probabilidad de recompra en la tienda')
as.datatable_widget(tab)

```

Gráficamente las cifras sobre el total de aquellos que utilizaron los probadores en tiendas físicas ...

```{r echo = FALSE}

df <- data %>%
    tab_subgroup(P7 %in% c(1,2)) %>% 
	tab_cells('|'=unvr(P7)) %>%
	tab_stat_cpct(total_row_position = 'none') %>%
	tab_pivot()
colnames(df) <- c('name','y')
df$y <- round(df$y,1)
highchart() %>%
    hc_title(text = '') %>% 
    hc_subtitle(text = 'Uso de probadores') %>% 
    hc_chart(type = 'pie', polar = FALSE, inverted = FALSE) %>% 
    hc_xAxis(categories = df$name) %>%
    hc_add_series(df,name = "Valor", showInLegend = FALSE, innerSize='75%',dataLabels = list(format="{point.name}<br>({point.y}%)"))%>%
    hc_credits(enabled=TRUE, text='InvestigaOnline.com', href ='https://www.investigaonline.com') %>%
    hc_exporting(enabled=TRUE)
```
