---
title: "Resultados (08)"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

El objetivo 08 hacía referencia a la evaluación de la atención al cliente tanto en el entorno web como en el entorno físico.

```{r echo = FALSE}
tab <- data %>%
    tab_subgroup(R1C==1) %>% 
    tab_row_label('Web') %>% 
	tab_cells(P8) %>%
	tab_stat_cpct(label='%casos') %>%
    tab_cells(P8) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_subgroup(R1C==2) %>% 
    tab_row_label('Física') %>% 
	tab_cells(P8) %>%
	tab_stat_cpct(label='%casos') %>%
    tab_cells(P8) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_pivot() %>%
    tab_caption('Necesidad de ayuda del SAC')
as.datatable_widget(tab)

tab <- data %>%
    tab_subgroup(R1C==1) %>% 
    tab_row_label('Web') %>% 
	tab_cells(P9) %>%
	tab_stat_cpct(label='%casos') %>%
    tab_cells(P9) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_subgroup(R1C==2) %>% 
    tab_row_label('Física') %>% 
	tab_cells(P9) %>%
	tab_stat_cpct(label='%casos') %>%
    tab_cells(P9) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_pivot() %>%
    tab_caption('Facilidad de localización')
as.datatable_widget(tab)

tab <- data %>%
    tab_subgroup(R1C==1) %>% 
    tab_row_label('Web') %>% 
	tab_cells(P10) %>%
	tab_stat_cpct(label='%casos') %>%
    tab_cells(P10) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_subgroup(R1C==2) %>% 
    tab_row_label('Física') %>% 
	tab_cells(P10) %>%
	tab_stat_cpct(label='%casos') %>%
    tab_cells(P10) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_pivot() %>%
    tab_caption('Canal utilizado')
as.datatable_widget(tab)

tab <- data %>%
    tab_subgroup(R1C==1) %>% 
    tab_row_label('Web') %>% 
	tab_cells(P11) %>%
	tab_stat_cpct(label='%casos') %>%
    tab_cells(P11) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_subgroup(R1C==2) %>% 
    tab_row_label('Física') %>% 
	tab_cells(P11) %>%
	tab_stat_cpct(label='%casos') %>%
    tab_cells(P11) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_pivot() %>%
    tab_caption('Tiempo en ser atendido')
as.datatable_widget(tab)

tab <- data %>%
    tab_subgroup(R1C==1) %>% 
    tab_row_label('Web') %>% 
	tab_cells(P12) %>%
	tab_stat_cpct(label='%casos') %>%
    tab_cells(P12) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_subgroup(R1C==2) %>% 
    tab_row_label('Física') %>% 
	tab_cells(P12) %>%
	tab_stat_cpct(label='%casos') %>%
    tab_cells(P12) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_pivot() %>%
    tab_caption('Atención al primer contacto')
as.datatable_widget(tab)


tab <- data %>%
    tab_subgroup(R1C==1) %>% 
    tab_row_label('Web') %>% 
	tab_cells(P12B) %>%
	tab_stat_mean() %>%
    tab_subgroup(R1C==2) %>% 
    tab_row_label('Física') %>% 
	tab_cells(P12B) %>%
	tab_stat_mean() %>%
    tab_pivot() %>%
    tab_caption('Tiempo medio en gestión')
as.datatable_widget(tab)


tab0 <- data %>%
        tab_cells('|'=unvr(P13_1)) %>% 
        tab_stat_cpct(label=var_lab(P13_1), total_row_position='below') %>%
        tab_cells('|'=unvr(P13_2)) %>% 
        tab_stat_cpct(label=var_lab(P13_2), total_row_position='below') %>%
        tab_cells('|'=unvr(P13_3)) %>% 
        tab_stat_cpct(label=var_lab(P13_3), total_row_position='below') %>%
        tab_cells('|'=unvr(P13_4)) %>% 
        tab_stat_cpct(label=var_lab(P13_4), total_row_position='below') %>%
        tab_cells('|'=unvr(P13_5)) %>% 
        tab_stat_cpct(label=var_lab(P13_5), total_row_position='below') %>%
        tab_cells('|'=unvr(P13_6)) %>% 
        tab_stat_cpct(label=var_lab(P13_6), total_row_position='below') %>%
        tab_cells('|'=unvr(P14)) %>% 
        tab_stat_cpct(label=paste("Valoración de:  |",var_lab(P14)), total_row_position='below') %>%
        tab_pivot(stat_position='inside_columns') %>%
        t()
tab1 <- data %>%
    tab_cells(
        na_if(P13_1,gt(10)),
        na_if(P13_2,gt(10)),
        na_if(P13_3,gt(10)),
        na_if(P13_4,gt(10)),
        na_if(P13_5,gt(10)),
        na_if(P13_6,gt(10)),
        na_if(P14,gt(10))) %>% 
    tab_stat_mean() %>%
    tab_pivot()
tab1 <- tab1[,-1]
tab2 <- as.etable(cbind(tab0,tab1))
tab2 <- tab2[,-1]
tab2 <- rename(tab2, Total='#Total cases', Media='#Total')
tab2$row_labels <- str_replace_all(tab2$row_labels, "#Total\\|", "")
as.datatable_widget(tab2, escape=FALSE, caption=('Valoración del personal de servicio y SAC'))
```

Si analizamos el KPI derivado ...

```{r echo = FALSE}
tab <- data %>%
	tab_cells(KPIP13) %>%
	tab_stat_cpct(label='%casos') %>%
    tab_cells(KPIP13) %>%
    tab_stat_cases(label='casos') %>%
    tab_last_hstack() %>%
    tab_cells(KPIP13) %>%
    tab_stat_mean(label='KPI-P13') %>%
    tab_last_hstack() %>%
	tab_pivot() %>%
    tab_caption('Índice de Valoración del personal de servicio')
as.datatable_widget(tab)
```

```{r echo = FALSE}
df <- data %>%
	tab_cells('|'=unvr(KPIP13)) %>%
	tab_stat_cpct(label='% casos', total_row_position = 'none') %>%
	tab_pivot(stat_position = 'inside_columns')
colnames(df) <- c('name','y')
df$y <- round(df$y,1)
highchart() %>%
    hc_title(text = 'Índice de Valoración del proceso de pago del pedido') %>% 
    hc_subtitle(text = 'KPI-P13') %>% 
    hc_chart(type = 'pie', polar = FALSE, inverted = FALSE) %>% 
    hc_xAxis(categories = df$name) %>%
    hc_add_series(df,name = "Valor", showInLegend = FALSE, innerSize='75%',dataLabels = list(format="{point.name}<br>({point.y}%)"))%>%
    hc_tooltip(useHTML = TRUE,style = list(fontSize = "30px"),headerFormat = "",pointFormat = paste("<br><div style='text-align: center;'>Índice <b><br>",round(mean(data$KPIP13, na.rm = TRUE), 1),"</div>"),
               positioner = JS(
                  "function () {
                    xp =  this.chart.chartWidth/2 - this.label.width/2
                    yp =  this.chart.chartHeight/2 - this.label.height/2
                    return { x: xp, y: yp };
                  }")
               ,shadow = FALSE,borderWidth = 0,backgroundColor = "transparent",hideDelay = 9999) %>%
    hc_credits(enabled=TRUE, text='InvestigaOnline.com', href ='https://www.investigaonline.com') %>%
    hc_exporting(enabled=TRUE)
```

Si distribuimos la satisfacción por sexo / edad / canal /grupo los resultados con los siguientes:

```{r echo = FALSE}
tab <- data %>%
    tab_cols(total(),R2, R3REC, R1C, R1D) %>%
    tab_cells(na_if(P13MEAN, gt(10))) %>%
    tab_stat_mean_sd_n() %>%
    tab_last_sig_means() %>%
	tab_pivot() %>%
    t() %>%
    tab_caption('Perfil * Valoración del personal de servicio')
as.datatable_widget(tab)
```


