---
title: 'Descripción del análisis'
output: 
  html_document: 
    theme: flatly
    number_sections: yes
    df_print: kable
editor_options: 
  chunk_output_type: console
---

# Introducción

El presente trabajo se desarrolla con el objetivo de obtener las diferencias de percepción y satisfacción en el proceso de compra de la población de entre 16 y 65 años en las tiendas físicas u online en dos de las tres grandes cadenas nacionales de moda joven: TENDAM e INDITEX. Queda fuera del
análisis por expreso deseo del *cliente final* el grupo MANGO y el grupo H&M.

El análisis se repetirá 3 veces a lo largo de una temporada de negocio: Diciembre, Marzo y Julio. Se realiza un primer piloto del mismo a finales de octubre de 2021 y la primera ola a finales de noviembre y principios de diciembre de 2021, completándose (en el futuro) con una nueva oleada en marzo de 2022, a comparar con la primera ola de 2021.

El análisis se ha estructurado por objetivos, presentando los resultados más significativos en forma de tabla y/o gráfico. Se presentan finalmente las conclusiones más relevantes. Se establece un dashboard de control que contendrá los resultados más relevantes.

Dado el carácter académico de la investigación, la muestra será obtenida a través de los contactos de los alumnos de la asignatura de Plan de marketing en la Universitat Católica de València y los alumnos de Gestión de Proyectos de Investigación Comercial en el Máster Universitario en Marketing e Investigación de Mercados en la Universitat de València. Aproximadamente, se esperan unas 300 entrevistas en cada oleada.

Para el piloto, se ha utilizado una muestra de conveniencia de estudiantes de máster en la Universitat de València. No es tanto el objetivo en este piloto el de establecer las diferencias sino de detectar déficit en el instrumento de medición ofrecido.

# Software

Tanto para el dashboard como para el análisis de datos se ha utilizado R software. El informe es entregado en formato HTML. Para las pruebas inferenciales se ha utilizado la prueba Chi<sup>2</sup> y la prueba t para medias en muestras independientes con el objeto de detectar las posibles diferencias entre los perfiles detectados en la investigación a partir de las preguntas SEXO, EDAD, CANAL y CADENA. Los gráficos son exportables como
imagen.

# Propuesta de investigación

<iframe src="https://docs.google.com/document/d/e/2PACX-1vR5yaWTStnjZ9XvYtjXyXU5gYHMZm-2t2C3-bx_Vzw0Whr76bBO7BLjeoWE6RwC7LTTis1pHqgMiezc/pub?embedded=true" width=10124 height='9300'></iframe>
